import type { ManagedImage } from '../src/types';

export function getInitialSeedImages(): ManagedImage[] {
  const now = new Date().toISOString();

  return [
    // 1. Ana Səhifə Hero (home_hero)
    {
      id: 'img-hero-1',
      url: '/images/dreamart-toy-dekoru-qizili-altar.webp',
      filename: 'dreamart-toy-dekoru-qizili-altar.webp',
      altText: 'Qara-qızılı fonda parıltılı monoqram, qızılı heykəllər və ağ gül kaskadı ilə bəy-gəlin toy səhnəsi',
      section: 'home_hero',
      targetId: 'hero-slide-1',
      targetName: 'Əsas Slayd 1 - Dəbdəbəli Toy Səhnəsi',
      isCover: true,
      order: 1,
      format: 'webp',
      uploadedAt: now
    },
    {
      id: 'img-hero-2',
      url: '/images/dreamart-nisan-dekoru-fotozona.webp',
      filename: 'dreamart-nisan-dekoru-fotozona.webp',
      altText: 'Bej drapaj pərdələr, parlaq işıqlı hərflər, ağ qızılgüllər və şamlarla nişan fotozonası',
      section: 'home_hero',
      targetId: 'hero-slide-2',
      targetName: 'Əsas Slayd 2 - Romantik Nişan Fotozonası',
      isCover: false,
      order: 2,
      format: 'webp',
      uploadedAt: now
    },
    {
      id: 'img-hero-3',
      url: '/images/dreamart-zal-dekoru-tavan-instalyasiyasi.webp',
      filename: 'dreamart-zal-dekoru-tavan-instalyasiyasi.webp',
      altText: 'Asma dalğalı ağ tül tavan örtükləri və böyük kristal çilçıraqlarla monumental zal dekoru',
      section: 'home_hero',
      targetId: 'hero-slide-3',
      targetName: 'Əsas Slayd 3 - Monumental Zal İnstalyasiyası',
      isCover: false,
      order: 3,
      format: 'webp',
      uploadedAt: now
    },

    // 2. Xidmət Kateqoriyaları (category_cover)
    {
      id: 'img-cat-toy',
      url: '/images/dreamart-toy-dekoru-qizili-altar.webp',
      filename: 'dreamart-toy-dekoru-qizili-altar.webp',
      altText: 'Qara-qızılı fon, qızılı heykəllər və ağ qızılgüllərlə toy dekoru örtük şəkli',
      section: 'category_cover',
      targetId: 'toy-dekoru',
      targetName: 'Toy dekoru',
      isCover: true,
      order: 1,
      format: 'webp',
      uploadedAt: now
    },
    {
      id: 'img-cat-nisan',
      url: '/images/dreamart-nisan-dekoru-fotozona.webp',
      filename: 'dreamart-nisan-dekoru-fotozona.webp',
      altText: 'Bej drapaj pərdələr və işıqlı hərflərlə nişan dekoru örtük şəkli',
      section: 'category_cover',
      targetId: 'nisan-dekoru',
      targetName: 'Nişan dekoru',
      isCover: true,
      order: 1,
      format: 'webp',
      uploadedAt: now
    },
    {
      id: 'img-cat-xina',
      url: '/images/dreamart-monumental-toy-sehnesi-dekoru.webp',
      filename: 'dreamart-xina-dekoru-qapaq.webp',
      altText: 'Qızılı tağlar və kristal çilçıraqlarla xına mərasimi dekoru örtük şəkli',
      section: 'category_cover',
      targetId: 'xina-dekoru',
      targetName: 'Xına dekoru',
      isCover: true,
      order: 1,
      format: 'webp',
      uploadedAt: now
    },
    {
      id: 'img-cat-adgunu',
      url: '/images/dreamart-nisan-dekoru-fotozona.webp',
      filename: 'dreamart-ad-gunu-dekoru-qapaq.webp',
      altText: 'Krem drapaj parçalar və işıqlı hərflərlə ad günü fotozonası örtük şəkli',
      section: 'category_cover',
      targetId: 'ad-gunu-dekoru',
      targetName: 'Ad günü dekoru',
      isCover: true,
      order: 1,
      format: 'webp',
      uploadedAt: now
    },
    {
      id: 'img-cat-korporativ',
      url: '/images/dreamart-qala-gecesi-samdan-dekoru.webp',
      filename: 'dreamart-qala-gecesi-samdan-dekoru.webp',
      altText: 'Büllur şamdanlar və qara süfrəli korporativ qala gecəsi dekoru örtük şəkli',
      section: 'category_cover',
      targetId: 'korporativ-dekor',
      targetName: 'Korporativ dekor',
      isCover: true,
      order: 1,
      format: 'webp',
      uploadedAt: now
    },
    {
      id: 'img-cat-zal',
      url: '/images/dreamart-zal-dekoru-tavan-instalyasiyasi.webp',
      filename: 'dreamart-zal-dekoru-tavan-instalyasiyasi.webp',
      altText: 'Dalğalı ağ tül və kristal çilçıraqlarla böyük şadlıq sarayı və zal dekorasiyası örtük şəkli',
      section: 'category_cover',
      targetId: 'zal-dekoru',
      targetName: 'Zal dekoru',
      isCover: true,
      order: 1,
      format: 'webp',
      uploadedAt: now
    },
    {
      id: 'img-cat-xonca',
      url: '/images/xonca-xidmeti-cover.jpg',
      filename: 'dreamart-xonca-xidmeti-qapaq.webp',
      altText: 'Oymalı qızılı sini, ağ-çəhrayı qızılgüllər və şamlarla milli və müasir xonça xidməti örtük şəkli',
      section: 'category_cover',
      targetId: 'xonca-xidmeti',
      targetName: 'Xonça xidməti',
      isCover: true,
      order: 1,
      format: 'webp',
      uploadedAt: now
    },

    // 3. Dekor Layihələri (decor_project)
    {
      id: 'img-decor-1-cover',
      url: '/images/dreamart-toy-dekoru-qizili-altar.webp',
      filename: 'dreamart-toy-dekoru-qizili-altar.webp',
      altText: 'Qara-qızılı fon, parıltılı monoqram, iki qızılı əl heykəli, ağ gül kaskadı və şüşə şamdanlarla bəy-gəlin toy səhnəsi',
      section: 'decor_project',
      targetId: 'decor-1',
      targetName: 'Qızılı Heykəllər və Ağ Güllərlə Dəbdəbəli Toy Səhnəsi',
      isCover: true,
      order: 1,
      format: 'webp',
      uploadedAt: now
    },
    {
      id: 'img-decor-1-gal-1',
      url: '/images/dreamart-monumental-toy-sehnesi-dekoru.webp',
      filename: 'dreamart-monumental-toy-sehnesi-dekoru.webp',
      altText: 'Qızılı tağlar, kristal çilçıraqlar və pilləli şamlarla monumental toy səhnəsi',
      section: 'decor_project',
      targetId: 'decor-1',
      targetName: 'Qızılı Heykəllər və Ağ Güllərlə Dəbdəbəli Toy Səhnəsi',
      isCover: false,
      order: 2,
      format: 'webp',
      uploadedAt: now
    },
    {
      id: 'img-decor-1-gal-2',
      url: '/images/dreamart-bey-gelin-masasi-cicek-tagi.webp',
      filename: 'dreamart-bey-gelin-masasi-cicek-tagi.webp',
      altText: 'Dairəvi çiçək tağları və büllur çilçıraqlarla bəzədilmiş bəy-gəlin masası',
      section: 'decor_project',
      targetId: 'decor-1',
      targetName: 'Qızılı Heykəllər və Ağ Güllərlə Dəbdəbəli Toy Səhnəsi',
      isCover: false,
      order: 3,
      format: 'webp',
      uploadedAt: now
    },
    {
      id: 'img-decor-2-cover',
      url: '/images/dreamart-nisan-dekoru-fotozona.webp',
      filename: 'dreamart-nisan-dekoru-fotozona.webp',
      altText: 'Bej drapaj pərdələr, işıqlı neon hərflər, ağ qızılgüllər və gümüşü şamdanlarla nişan fotozonası',
      section: 'decor_project',
      targetId: 'decor-2',
      targetName: 'Şampan-Bej Drapaj və İşıqlı Hərflərlə Nişan Fotozonası',
      isCover: true,
      order: 1,
      format: 'webp',
      uploadedAt: now
    },
    {
      id: 'img-decor-2-gal-1',
      url: '/images/dreamart-bey-gelin-masasi-cicek-tagi.webp',
      filename: 'dreamart-bey-gelin-masasi-cicek-tagi.webp',
      altText: 'Dairəvi çiçək tağları və büllur çilçıraqlı zərif nişan masası',
      section: 'decor_project',
      targetId: 'decor-2',
      targetName: 'Şampan-Bej Drapaj və İşıqlı Hərflərlə Nişan Fotozonası',
      isCover: false,
      order: 2,
      format: 'webp',
      uploadedAt: now
    },
    {
      id: 'img-decor-3-cover',
      url: '/images/dreamart-monumental-toy-sehnesi-dekoru.webp',
      filename: 'kraliyyet-mexmeri-xina-dekoru-main.webp',
      altText: 'Qızılı tağlar, kristal çilçıraqlar, ağ taxt kreslolar və çoxsaylı şamlarla tərtib edilmiş xına səhnəsi',
      section: 'decor_project',
      targetId: 'decor-3',
      targetName: 'Qızılı Tağlar və Kristal Çilçıraqlı Dəbdəbəli Xına Səhnəsi',
      isCover: true,
      order: 1,
      format: 'webp',
      uploadedAt: now
    },
    {
      id: 'img-decor-4-cover',
      url: '/images/dreamart-nisan-dekoru-fotozona.webp',
      filename: 'krem-qizili-ad-gunu-fotozona-main.webp',
      altText: 'Bej parçalar, işıqlı hərflər, ağ güllər və şamlarla işlənmiş ad günü fotozona dekoru',
      section: 'decor_project',
      targetId: 'decor-4',
      targetName: 'Krem-Qızılı Drapaj və İşıqlı Hərflərlə Ad Günü Guşəsi',
      isCover: true,
      order: 1,
      format: 'webp',
      uploadedAt: now
    },
    {
      id: 'img-decor-5-cover',
      url: '/images/dreamart-qala-gecesi-samdan-dekoru.webp',
      filename: 'dreamart-qala-gecesi-samdan-dekoru.webp',
      altText: 'Qara süfrə, hündür büllur şamdanlar, zərif qablar və ağ güllərlə tərtib olunmuş qala masası dekoru',
      section: 'decor_project',
      targetId: 'decor-5',
      targetName: 'Büllur Şamdanlar və Qara Süfrəli Qala Ziyafət Masası',
      isCover: true,
      order: 1,
      format: 'webp',
      uploadedAt: now
    },
    {
      id: 'img-decor-5-gal-1',
      url: '/images/dreamart-restoran-qonaq-masasi-dekoru.webp',
      filename: 'dreamart-restoran-qonaq-masasi-dekoru.webp',
      altText: 'Zümrüd yaşıl süfrə və hündür gül vazalı qonaq masası tərtibatı',
      section: 'decor_project',
      targetId: 'decor-5',
      targetName: 'Büllur Şamdanlar və Qara Süfrəli Qala Ziyafət Masası',
      isCover: false,
      order: 2,
      format: 'webp',
      uploadedAt: now
    },
    {
      id: 'img-decor-6-cover',
      url: '/images/dreamart-zal-dekoru-tavan-instalyasiyasi.webp',
      filename: 'dreamart-zal-dekoru-tavan-instalyasiyasi.webp',
      altText: 'Asma ağ tül tavan örtükləri, böyük kristal çilçıraqlar və şəffaf stullarla bəzədilmiş ziyafət zalı dekoru',
      section: 'decor_project',
      targetId: 'decor-6',
      targetName: 'Dalğalı Ağ Tül və Kristal Çilçıraqlı Monumental Zal Dekoru',
      isCover: true,
      order: 1,
      format: 'webp',
      uploadedAt: now
    },
    {
      id: 'img-decor-6-gal-1',
      url: '/images/dreamart-restoran-qonaq-masasi-dekoru.webp',
      filename: 'dreamart-restoran-qonaq-masasi-dekoru.webp',
      altText: 'Zümrüd yaşıl məxmər süfrə və hündür gül güldanlı masa dekoru',
      section: 'decor_project',
      targetId: 'decor-6',
      targetName: 'Dalğalı Ağ Tül və Kristal Çilçıraqlı Monumental Zal Dekoru',
      isCover: false,
      order: 2,
      format: 'webp',
      uploadedAt: now
    },
    {
      id: 'img-decor-6-gal-2',
      url: '/images/dreamart-banket-zali-goy-isiq-dekoru.webp',
      filename: 'dreamart-banket-zali-goy-isiq-dekoru.webp',
      altText: 'Göy arxitektur işıqlandırma, tavan gül kaskadı və kristal çilçıraqlarla banket zalı',
      section: 'decor_project',
      targetId: 'decor-6',
      targetName: 'Dalğalı Ağ Tül və Kristal Çilçıraqlı Monumental Zal Dekoru',
      isCover: false,
      order: 3,
      format: 'webp',
      uploadedAt: now
    },
    {
      id: 'img-decor-7-cover',
      url: 'https://images.unsplash.com/photo-1465495976277-4387d4b0b4c6?auto=format&fit=crop&w=1600&q=85',
      filename: 'aciq-hava-dag-menzereli-toy-altari-main.webp',
      altText: 'Açıq hava dağ mənzərəli toy altarı',
      section: 'decor_project',
      targetId: 'decor-7',
      targetName: 'Açıq Hava Dağ Mənzərəli Toy Altarı',
      isCover: true,
      order: 1,
      format: 'webp',
      uploadedAt: now
    },
    {
      id: 'img-decor-8-cover',
      url: '/images/dreamart-tebii-budag-agac-kompozisiyasi.webp',
      filename: 'dreamart-tebii-budag-agac-kompozisiyasi.webp',
      altText: 'Təbii ağac budaqları, sıx ağ qızılgüllər və klassik stullarla tərtib edilmiş intim mərasim masası dekoru',
      section: 'decor_project',
      targetId: 'decor-8',
      targetName: 'Təbii Ağac Budaqları və Sıx Ağ Güllərlə İntim Masa Dekoru',
      isCover: true,
      order: 1,
      format: 'webp',
      uploadedAt: now
    },
    {
      id: 'img-decor-9-cover',
      url: '/images/xonca-xidmeti-cover.jpg',
      filename: 'ekskluziv-bullur-qizili-xonca-main.webp',
      altText: 'Oymalı qızılı sini, ağ-çəhrayı təbii qızılgüllər və yanan şamlarla tərtib edilmiş toy və nişan xonçası',
      section: 'decor_project',
      targetId: 'decor-9',
      targetName: 'Oymalı Qızılı Sini və Canlı Güllərlə Dəbdəbəli Xonça Tərtibatı',
      isCover: true,
      order: 1,
      format: 'webp',
      uploadedAt: now
    },

    // 4. Restoran / Məkan Layihələri (venue_project)
    {
      id: 'img-venue-meridian-cover',
      url: '/images/dreamart-monumental-toy-sehnesi-dekoru.webp',
      filename: 'dreamart-monumental-toy-sehnesi-dekoru.webp',
      altText: 'Meridian məkanında qızılı tağlar, kristal çilçıraqlar və pilləli şamlarla monumental toy səhnəsi',
      section: 'venue_project',
      targetId: 'meridian',
      targetName: 'Meridian Şadlıq Sarayı',
      isCover: true,
      order: 1,
      format: 'webp',
      uploadedAt: now
    },
    {
      id: 'img-venue-meridian-gal-1',
      url: '/images/dreamart-toy-dekoru-qizili-altar.webp',
      filename: 'dreamart-toy-dekoru-qizili-altar.webp',
      altText: 'Meridian məkanında qara-qızılı fon, parıltılı monoqram, ağ gül kaskadı və şüşə şamdanlarla toy səhnəsi',
      section: 'venue_project',
      targetId: 'meridian',
      targetName: 'Meridian Şadlıq Sarayı',
      isCover: false,
      order: 2,
      format: 'webp',
      uploadedAt: now
    },
    {
      id: 'img-venue-meridian-gal-2',
      url: '/images/dreamart-banket-zali-goy-isiq-dekoru.webp',
      filename: 'dreamart-banket-zali-goy-isiq-dekoru.webp',
      altText: 'Meridian banket zalında göy və kəhrəba işıqlar, tavan gül kaskadı və kristal çilçıraqlar',
      section: 'venue_project',
      targetId: 'meridian',
      targetName: 'Meridian Şadlıq Sarayı',
      isCover: false,
      order: 3,
      format: 'webp',
      uploadedAt: now
    },
    {
      id: 'img-venue-by-meridian-cover',
      url: '/images/dreamart-bey-gelin-masasi-cicek-tagi.webp',
      filename: 'dreamart-bey-gelin-masasi-cicek-tagi.webp',
      altText: 'By Meridian məkanında dairəvi ağ-çəhrayı çiçək tağları və büllur çilçıraqlı bəy-gəlin masası',
      section: 'venue_project',
      targetId: 'by-meridian',
      targetName: 'By Meridian',
      isCover: true,
      order: 1,
      format: 'webp',
      uploadedAt: now
    },
    {
      id: 'img-venue-by-meridian-gal-1',
      url: '/images/dreamart-nisan-dekoru-fotozona.webp',
      filename: 'dreamart-nisan-dekoru-fotozona.webp',
      altText: 'By Meridian məkanında bej drapaj pərdələr və işıqlı neon hərflərlə nişan fotozonası',
      section: 'venue_project',
      targetId: 'by-meridian',
      targetName: 'By Meridian',
      isCover: false,
      order: 2,
      format: 'webp',
      uploadedAt: now
    },
    {
      id: 'img-venue-by-meridian-gal-2',
      url: '/images/dreamart-tebii-budag-agac-kompozisiyasi.webp',
      filename: 'dreamart-tebii-budag-agac-kompozisiyasi.webp',
      altText: 'By Meridian məkanında təbii ağac budaqları və sıx ağ qızılgüllərlə masa kompozisiyası',
      section: 'venue_project',
      targetId: 'by-meridian',
      targetName: 'By Meridian',
      isCover: false,
      order: 3,
      format: 'webp',
      uploadedAt: now
    },
    {
      id: 'img-venue-bagcali-cover',
      url: '/images/dreamart-restoran-qonaq-masasi-dekoru.webp',
      filename: 'dreamart-restoran-qonaq-masasi-dekoru.webp',
      altText: 'Bağçalı Sarayda zümrüd yaşıl məxmər süfrə və hündür gül vazalı qonaq masası tərtibatı',
      section: 'venue_project',
      targetId: 'bagcali-saray',
      targetName: 'Bağçalı Saray',
      isCover: true,
      order: 1,
      format: 'webp',
      uploadedAt: now
    },
    {
      id: 'img-venue-bagcali-gal-1',
      url: '/images/dreamart-qala-gecesi-samdan-dekoru.webp',
      filename: 'dreamart-qala-gecesi-samdan-dekoru.webp',
      altText: 'Bağçalı Sarayda çoxqollu büllur şamdan və qara süfrəli ziyafət masası dekoru',
      section: 'venue_project',
      targetId: 'bagcali-saray',
      targetName: 'Bağçalı Saray',
      isCover: false,
      order: 2,
      format: 'webp',
      uploadedAt: now
    },
    {
      id: 'img-venue-boyuk-cover',
      url: '/images/dreamart-zal-dekoru-tavan-instalyasiyasi.webp',
      filename: 'dreamart-zal-dekoru-tavan-instalyasiyasi.webp',
      altText: 'Böyük Saray şadlıq sarayında asma ağ tül tavan örtükləri və böyük kristal çilçıraqlar',
      section: 'venue_project',
      targetId: 'boyuk-saray',
      targetName: 'Böyük Saray',
      isCover: true,
      order: 1,
      format: 'webp',
      uploadedAt: now
    },
    {
      id: 'img-venue-boyuk-gal-1',
      url: '/images/dreamart-banket-zali-goy-isiq-dekoru.webp',
      filename: 'dreamart-banket-zali-goy-isiq-dekoru.webp',
      altText: 'Böyük Saray banket zalında göy arxitektur işıqlandırma və hündür gül güldanlı qonaq masası',
      section: 'venue_project',
      targetId: 'boyuk-saray',
      targetName: 'Böyük Saray',
      isCover: false,
      order: 2,
      format: 'webp',
      uploadedAt: now
    },
    {
      id: 'img-venue-green-city-cover',
      url: 'https://images.unsplash.com/photo-1464366400600-7168b8af9bc3?auto=format&fit=crop&w=1600&q=85',
      filename: 'green-city-acig-hava-dekor-cover.webp',
      altText: 'Green City açıq hava tədbir məkanı dekoru',
      section: 'venue_project',
      targetId: 'green-city',
      targetName: 'Green City',
      isCover: true,
      order: 1,
      format: 'webp',
      uploadedAt: now
    },
    {
      id: 'img-venue-yegane-cover',
      url: 'https://images.unsplash.com/photo-1511285560929-80b456fea0bc?auto=format&fit=crop&w=1600&q=85',
      filename: 'yegane-sadliq-sarayi-cover.webp',
      altText: 'Yeganə şadlıq sarayı dekoru örtük şəkli',
      section: 'venue_project',
      targetId: 'yegane',
      targetName: 'Yeganə Şadlıq Sarayı',
      isCover: true,
      order: 1,
      format: 'webp',
      uploadedAt: now
    },

    // 5. Xonça Xidməti (xonca_service)
    {
      id: 'img-xonca-main',
      url: '/images/xonca-xidmeti-cover.jpg',
      filename: 'premium-xonca-xidmeti-main.webp',
      altText: 'Qara mərmər masa üzərində oymalı qızılı sini, günbəz qapaqlı qab, milli şirniyyatlar və ağ-çəhrayı qızılgüllərlə dəbdəbəli xonça',
      section: 'xonca_service',
      targetId: 'xonca-main',
      targetName: 'Oymalı Qızılı Sini və Canlı Güllərlə Dəbdəbəli Xonça',
      isCover: true,
      order: 1,
      format: 'webp',
      uploadedAt: now
    },
    {
      id: 'img-xonca-gal-1',
      url: '/images/dreamart-tebii-budag-agac-kompozisiyasi.webp',
      filename: 'dreamart-tebii-budag-agac-kompozisiyasi.webp',
      altText: 'Təbii ağac budaqları, sıx ağ qızılgüllər və zərif stendlərlə xonça guşəsi',
      section: 'xonca_service',
      targetId: 'xonca-main',
      targetName: 'Təbii Ağac Budaqları və Sıx Ağ Güllərlə Masa Dekoru',
      isCover: false,
      order: 2,
      format: 'webp',
      uploadedAt: now
    },

    // 6. Portfolio Lookbook (portfolio_lookbook) - contains all 9 real DreamArt Events works
    {
      id: 'img-portfolio-1',
      url: '/images/dreamart-toy-dekoru-qizili-altar.webp',
      filename: 'dreamart-toy-dekoru-qizili-altar.webp',
      altText: 'Qara fon üzərində qızılı saplı pərdələr, parıltılı monoqram, iki qızılı əl heykəli, ağ gül kaskadı və hündür şüşə şamdanlarla dəbdəbəli bəy-gəlin toy səhnəsi',
      section: 'portfolio_lookbook',
      targetId: 'portfolio-showcase',
      targetName: 'Qızılı Heykəllər və Ağ Güllərlə Dəbdəbəli Toy Səhnəsi',
      isCover: true,
      order: 1,
      format: 'webp',
      uploadedAt: now
    },
    {
      id: 'img-portfolio-2',
      url: '/images/dreamart-nisan-dekoru-fotozona.webp',
      filename: 'dreamart-nisan-dekoru-fotozona.webp',
      altText: 'Bej və şampan tonlarında zərif drapaj pərdələr, parıldayan işıqlı hərflər, hündür sütunlarda ağ qızılgüllər və pilləli şamlarla romantik nişan fotozonası',
      section: 'portfolio_lookbook',
      targetId: 'portfolio-showcase',
      targetName: 'Şampan-Bej Drapaj və İşıqlı Hərflərlə Nişan Fotozonası',
      isCover: false,
      order: 2,
      format: 'webp',
      uploadedAt: now
    },
    {
      id: 'img-portfolio-3',
      url: '/images/dreamart-zal-dekoru-tavan-instalyasiyasi.webp',
      filename: 'dreamart-zal-dekoru-tavan-instalyasiyasi.webp',
      altText: 'Zal tavanından dalğavari asılmış ağ tül örtüklər, böyük kristal çilçıraqlar, şəffaf stullar və ağ gül buketləri ilə bəzədilmiş geniş ziyafət zalı',
      section: 'portfolio_lookbook',
      targetId: 'portfolio-showcase',
      targetName: 'Dalğalı Ağ Tül və Kristal Çilçıraqlı Monumental Zal Dekoru',
      isCover: false,
      order: 3,
      format: 'webp',
      uploadedAt: now
    },
    {
      id: 'img-portfolio-4',
      url: '/images/dreamart-monumental-toy-sehnesi-dekoru.webp',
      filename: 'dreamart-monumental-toy-sehnesi-dekoru.webp',
      altText: 'Qızılı pərdə fonu, dörd işıqlı tağ konstruksiyası, kristal çilçıraqlar, ağ taxt kreslolar və pillələrdə çoxsaylı yanan şamlarla möhtəşəm səhnə',
      section: 'portfolio_lookbook',
      targetId: 'portfolio-showcase',
      targetName: 'Qızılı Tağlar və Kristal Çilçıraqlı Dəbdəbəli Səhnə',
      isCover: false,
      order: 4,
      format: 'webp',
      uploadedAt: now
    },
    {
      id: 'img-portfolio-5',
      url: '/images/dreamart-bey-gelin-masasi-cicek-tagi.webp',
      filename: 'dreamart-bey-gelin-masasi-cicek-tagi.webp',
      altText: 'Drapajlı ağ arxa fon, masanı dövrələyən sıx ağ və çəhrayı qızılgül tağları, asma büllur çilçıraqlar və güzgülü masa üzərində yanan şamlar',
      section: 'portfolio_lookbook',
      targetId: 'portfolio-showcase',
      targetName: 'Ağ-Çəhrayı Güllərlə Dairəvi Tağlı Bəy-Gəlin Masası',
      isCover: false,
      order: 5,
      format: 'webp',
      uploadedAt: now
    },
    {
      id: 'img-portfolio-6',
      url: '/images/dreamart-restoran-qonaq-masasi-dekoru.webp',
      filename: 'dreamart-restoran-qonaq-masasi-dekoru.webp',
      altText: 'Zümrüd yaşıl məxmər süfrəli ziyafət masası, mərkəzdə hündür şüşə vazada ağ qızılgül buketi, şəffaf stullar və fonda parıldayan kristal çilçıraq',
      section: 'portfolio_lookbook',
      targetId: 'portfolio-showcase',
      targetName: 'Zümrüd Yaşıl Məxmər Süfrə və Hündür Vaza Gülləri',
      isCover: false,
      order: 6,
      format: 'webp',
      uploadedAt: now
    },
    {
      id: 'img-portfolio-7',
      url: '/images/dreamart-qala-gecesi-samdan-dekoru.webp',
      filename: 'dreamart-qala-gecesi-samdan-dekoru.webp',
      altText: 'Qara ziyafət masası üzərində hündür çoxqollu büllur şamdan, incə şamlar, qızılı aksessuarlar və arxa fonda dalğalanan ağ səhnə pərdələri',
      section: 'portfolio_lookbook',
      targetId: 'portfolio-showcase',
      targetName: 'Büllur Şamdanlar və Qara Süfrəli Qala Masası',
      isCover: false,
      order: 7,
      format: 'webp',
      uploadedAt: now
    },
    {
      id: 'img-portfolio-8',
      url: '/images/dreamart-banket-zali-goy-isiq-dekoru.webp',
      filename: 'dreamart-banket-zali-goy-isiq-dekoru.webp',
      altText: 'Göy və kəhrəba işıqlı tağvari memarlıq elementləri, tavandan asılan ağ gül kaskadı, kristal çilçıraqlar və hündür gül vazalı qonaq masası',
      section: 'portfolio_lookbook',
      targetId: 'portfolio-showcase',
      targetName: 'Göy İşıqlı Tağlar və Tavan Gül Kaskadlı Banket Zalı',
      isCover: false,
      order: 8,
      format: 'webp',
      uploadedAt: now
    },
    {
      id: 'img-portfolio-9',
      url: '/images/dreamart-tebii-budag-agac-kompozisiyasi.webp',
      filename: 'dreamart-tebii-budag-agac-kompozisiyasi.webp',
      altText: 'Masa mərkəzində ucalan təbii ağac budaqları, çətirində və ətəyində ağ-krem qızılgüllər, dairəvi güzgülü altlıq və klassik oymalı stullar',
      section: 'portfolio_lookbook',
      targetId: 'portfolio-showcase',
      targetName: 'Təbii Ağac Budaqları və Sıx Ağ Güllərlə Masa Dekoru',
      isCover: false,
      order: 9,
      format: 'webp',
      uploadedAt: now
    },
    {
      id: 'img-portfolio-10',
      url: '/images/xonca-xidmeti-cover.jpg',
      filename: 'premium-xonca-xidmeti-main.webp',
      altText: 'Qara mərmər masa üzərində oymalı qızılı xonça sinisi, günbəz qapaqlı qab, milli şirniyyatlar, ağ-çəhrayı qızılgüllər və yanan şüşə şamdanlar',
      section: 'portfolio_lookbook',
      targetId: 'portfolio-showcase',
      targetName: 'Oymalı Qızılı Sini və Canlı Güllərlə Dəbdəbəli Xonça',
      isCover: false,
      order: 10,
      format: 'webp',
      uploadedAt: now
    },

    // 7. Region Xidməti (regional_service)
    {
      id: 'img-regional-main',
      url: '/images/azerbaijan-regional-cover.jpg',
      filename: 'azerbaijan-regional-dekor-cover.webp',
      altText: 'Azərbaycan regional dekorasiya və loqistika xidməti',
      section: 'regional_service',
      targetId: 'regional-main',
      targetName: 'Azərbaycan Regional Xidmət Banneri',
      isCover: true,
      order: 1,
      format: 'webp',
      uploadedAt: now
    }
  ];
}
