import type { ManagedImage } from '../src/types';

export function getInitialSeedImages(): ManagedImage[] {
  const now = new Date().toISOString();

  return [
    // 1. Ana Səhifə Hero (home_hero)
    {
      id: 'img-hero-1',
      url: '/images/dreamart-toy-dekoru-qizili-altar.webp',
      filename: 'dreamart-toy-dekoru-qizili-altar.webp',
      altText: 'DreamArt Events qızılı tağ və dəbdəbəli bəy-gəlin masası toy dekoru əsas banner',
      section: 'home_hero',
      targetId: 'hero-slide-1',
      targetName: 'Əsas Slayd 1 - Zövqlü Dekor Həlləri',
      isCover: true,
      order: 1,
      format: 'webp',
      uploadedAt: now
    },
    {
      id: 'img-hero-2',
      url: '/images/dreamart-nisan-dekoru-fotozona.webp',
      filename: 'dreamart-nisan-dekoru-fotozona.webp',
      altText: 'DreamArt Events zərif bej parçalar və neon işıqlı nişan dekoru və fotozona',
      section: 'home_hero',
      targetId: 'hero-slide-2',
      targetName: 'Əsas Slayd 2 - Müasir Zəriflik',
      isCover: false,
      order: 2,
      format: 'webp',
      uploadedAt: now
    },
    {
      id: 'img-hero-3',
      url: '/images/dreamart-zal-dekoru-tavan-instalyasiyasi.webp',
      filename: 'dreamart-zal-dekoru-tavan-instalyasiyasi.webp',
      altText: 'DreamArt Events böyük şadlıq zalı tavan pərdələri və çilçıraq zal dekoru',
      section: 'home_hero',
      targetId: 'hero-slide-3',
      targetName: 'Əsas Slayd 3 - Böyük Zallar və İnstalyasiyalar',
      isCover: false,
      order: 3,
      format: 'webp',
      uploadedAt: now
    },

    // 2. Xidmət Kateqoriyaları (category_cover)
    {
      id: 'img-cat-toy',
      url: '/images/dreamart-toy-dekoru-qizili-altar.webp',
      filename: 'dreamart-toy-dekoru-qizili-altar.webp',
      altText: 'DreamArt Events toy dekoru örtük şəkli',
      section: 'category_cover',
      targetId: 'toy-dekoru',
      targetName: 'Toy dekoru',
      isCover: true,
      order: 1,
      format: 'webp',
      uploadedAt: now
    },
    {
      id: 'img-cat-nisan',
      url: '/images/dreamart-nisan-dekoru-fotozona.webp',
      filename: 'dreamart-nisan-dekoru-fotozona.webp',
      altText: 'DreamArt Events nişan dekoru örtük şəkli',
      section: 'category_cover',
      targetId: 'nisan-dekoru',
      targetName: 'Nişan dekoru',
      isCover: true,
      order: 1,
      format: 'webp',
      uploadedAt: now
    },
    {
      id: 'img-cat-xina',
      url: 'https://images.unsplash.com/photo-1583939003579-730e3918a45a?auto=format&fit=crop&w=1600&q=85',
      filename: 'dreamart-xina-dekoru-qapaq.webp',
      altText: 'DreamArt Events xına mərasimi dekoru örtük şəkli',
      section: 'category_cover',
      targetId: 'xina-dekoru',
      targetName: 'Xına dekoru',
      isCover: true,
      order: 1,
      format: 'webp',
      uploadedAt: now
    },
    {
      id: 'img-cat-adgunu',
      url: 'https://images.unsplash.com/photo-1530103862676-de8c9debad1d?auto=format&fit=crop&w=1600&q=85',
      filename: 'dreamart-ad-gunu-dekoru-qapaq.webp',
      altText: 'DreamArt Events ad günü və yubiley fotozonası örtük şəkli',
      section: 'category_cover',
      targetId: 'ad-gunu-dekoru',
      targetName: 'Ad günü dekoru',
      isCover: true,
      order: 1,
      format: 'webp',
      uploadedAt: now
    },
    {
      id: 'img-cat-korporativ',
      url: '/images/dreamart-qala-gecesi-samdan-dekoru.webp',
      filename: 'dreamart-qala-gecesi-samdan-dekoru.webp',
      altText: 'DreamArt Events korporativ tədbir və qala gecəsi dekoru örtük şəkli',
      section: 'category_cover',
      targetId: 'korporativ-dekor',
      targetName: 'Korporativ dekor',
      isCover: true,
      order: 1,
      format: 'webp',
      uploadedAt: now
    },
    {
      id: 'img-cat-zal',
      url: '/images/dreamart-zal-dekoru-tavan-instalyasiyasi.webp',
      filename: 'dreamart-zal-dekoru-tavan-instalyasiyasi.webp',
      altText: 'DreamArt Events böyük şadlıq sarayı və zal dekorasiyası örtük şəkli',
      section: 'category_cover',
      targetId: 'zal-dekoru',
      targetName: 'Zal dekoru',
      isCover: true,
      order: 1,
      format: 'webp',
      uploadedAt: now
    },
    {
      id: 'img-cat-xonca',
      url: '/images/xonca-xidmeti-cover.jpg',
      filename: 'dreamart-xonca-xidmeti-qapaq.webp',
      altText: 'DreamArt Events milli və müasir xonça xidməti örtük şəkli',
      section: 'category_cover',
      targetId: 'xonca-xidmeti',
      targetName: 'Xonça xidməti',
      isCover: true,
      order: 1,
      format: 'webp',
      uploadedAt: now
    },

    // 3. Dekor Layihələri (decor_project)
    {
      id: 'img-decor-1-cover',
      url: '/images/dreamart-toy-dekoru-qizili-altar.webp',
      filename: 'dreamart-toy-dekoru-qizili-altar.webp',
      altText: 'DreamArt Events qızılı tağ və dəbdəbəli bəy-gəlin masası toy dekoru',
      section: 'decor_project',
      targetId: 'decor-1',
      targetName: 'Ağ Qızılgül və Zərif Şamlı Toy Altarı',
      isCover: true,
      order: 1,
      format: 'webp',
      uploadedAt: now
    },
    {
      id: 'img-decor-1-gal-1',
      url: '/images/dreamart-monumental-toy-sehnesi-dekoru.webp',
      filename: 'dreamart-monumental-toy-sehnesi-dekoru.webp',
      altText: 'DreamArt Events monumental toy səhnəsi və pilləli şamlar',
      section: 'decor_project',
      targetId: 'decor-1',
      targetName: 'Ağ Qızılgül və Zərif Şamlı Toy Altarı',
      isCover: false,
      order: 2,
      format: 'webp',
      uploadedAt: now
    },
    {
      id: 'img-decor-1-gal-2',
      url: '/images/dreamart-bey-gelin-masasi-cicek-tagi.webp',
      filename: 'dreamart-bey-gelin-masasi-cicek-tagi.webp',
      altText: 'DreamArt Events dairəvi çiçək tağları və büllur çilçıraqlı bəy-gəlin masası',
      section: 'decor_project',
      targetId: 'decor-1',
      targetName: 'Ağ Qızılgül və Zərif Şamlı Toy Altarı',
      isCover: false,
      order: 3,
      format: 'webp',
      uploadedAt: now
    },
    {
      id: 'img-decor-2-cover',
      url: '/images/dreamart-nisan-dekoru-fotozona.webp',
      filename: 'dreamart-nisan-dekoru-fotozona.webp',
      altText: 'DreamArt Events zərif bej parçalar və neon işıqlı nişan dekoru və fotozona',
      section: 'decor_project',
      targetId: 'decor-2',
      targetName: 'Pudra Çəhrayı və Qızılı Pastel Nişan Masası',
      isCover: true,
      order: 1,
      format: 'webp',
      uploadedAt: now
    },
    {
      id: 'img-decor-2-gal-1',
      url: '/images/dreamart-bey-gelin-masasi-cicek-tagi.webp',
      filename: 'dreamart-bey-gelin-masasi-cicek-tagi.webp',
      altText: 'DreamArt Events zərif nişan masası və çiçək tağları',
      section: 'decor_project',
      targetId: 'decor-2',
      targetName: 'Pudra Çəhrayı və Qızılı Pastel Nişan Masası',
      isCover: false,
      order: 2,
      format: 'webp',
      uploadedAt: now
    },
    {
      id: 'img-decor-3-cover',
      url: 'https://images.unsplash.com/photo-1583939003579-730e3918a45a?auto=format&fit=crop&w=1600&q=85',
      filename: 'kraliyyet-mexmeri-xina-dekoru-main.webp',
      altText: 'Kraliyyət məxməri və şam kompozisiyalı xına dekoru',
      section: 'decor_project',
      targetId: 'decor-3',
      targetName: 'Kraliyyət Məxməri və Şam Kompozisiyalı Xına Dekoru',
      isCover: true,
      order: 1,
      format: 'webp',
      uploadedAt: now
    },
    {
      id: 'img-decor-4-cover',
      url: 'https://images.unsplash.com/photo-1530103862676-de8c9debad1d?auto=format&fit=crop&w=1600&q=85',
      filename: 'krem-qizili-ad-gunu-fotozona-main.webp',
      altText: 'Krem və qızılı işıqlı estetik ad günü fotozonası',
      section: 'decor_project',
      targetId: 'decor-4',
      targetName: 'Krem Və Qızılı İşıqlı Estetik Ad Günü Fotozonası',
      isCover: true,
      order: 1,
      format: 'webp',
      uploadedAt: now
    },
    {
      id: 'img-decor-5-cover',
      url: '/images/dreamart-qala-gecesi-samdan-dekoru.webp',
      filename: 'dreamart-qala-gecesi-samdan-dekoru.webp',
      altText: 'DreamArt Events büllur şamdanlar və zərif qab-qacaqla korporativ qala dekoru',
      section: 'decor_project',
      targetId: 'decor-5',
      targetName: 'Qala Şam Yeməyi və Korporativ Tədbir Tərtibatı',
      isCover: true,
      order: 1,
      format: 'webp',
      uploadedAt: now
    },
    {
      id: 'img-decor-5-gal-1',
      url: '/images/dreamart-restoran-qonaq-masasi-dekoru.webp',
      filename: 'dreamart-restoran-qonaq-masasi-dekoru.webp',
      altText: 'DreamArt Events qala gecəsi qonaq masası tərtibatı',
      section: 'decor_project',
      targetId: 'decor-5',
      targetName: 'Qala Şam Yeməyi və Korporativ Tədbir Tərtibatı',
      isCover: false,
      order: 2,
      format: 'webp',
      uploadedAt: now
    },
    {
      id: 'img-decor-6-cover',
      url: '/images/dreamart-zal-dekoru-tavan-instalyasiyasi.webp',
      filename: 'dreamart-zal-dekoru-tavan-instalyasiyasi.webp',
      altText: 'DreamArt Events böyük şadlıq zalı tavan pərdələri və çilçıraq zal dekoru',
      section: 'decor_project',
      targetId: 'decor-6',
      targetName: 'Panoramik Şadlıq Zalı və Tavan İşıq İnstalyasiyası',
      isCover: true,
      order: 1,
      format: 'webp',
      uploadedAt: now
    },
    {
      id: 'img-decor-6-gal-1',
      url: '/images/dreamart-restoran-qonaq-masasi-dekoru.webp',
      filename: 'dreamart-restoran-qonaq-masasi-dekoru.webp',
      altText: 'DreamArt Events zümrüd yaşıl məxmər süfrə və hündür gül güldanlı masa dekoru',
      section: 'decor_project',
      targetId: 'decor-6',
      targetName: 'Panoramik Şadlıq Zalı və Tavan İşıq İnstalyasiyası',
      isCover: false,
      order: 2,
      format: 'webp',
      uploadedAt: now
    },
    {
      id: 'img-decor-6-gal-2',
      url: '/images/dreamart-banket-zali-goy-isiq-dekoru.webp',
      filename: 'dreamart-banket-zali-goy-isiq-dekoru.webp',
      altText: 'DreamArt Events dəbdəbəli banket zalı, qonaq masası və çilçıraq tərtibatı',
      section: 'decor_project',
      targetId: 'decor-6',
      targetName: 'Panoramik Şadlıq Zalı və Tavan İşıq İnstalyasiyası',
      isCover: false,
      order: 3,
      format: 'webp',
      uploadedAt: now
    },
    {
      id: 'img-decor-7-cover',
      url: 'https://images.unsplash.com/photo-1465495976277-4387d4b0b4c6?auto=format&fit=crop&w=1600&q=85',
      filename: 'aciq-hava-dag-menzereli-toy-altari-main.webp',
      altText: 'Açıq hava dağ mənzərəli toy altarı',
      section: 'decor_project',
      targetId: 'decor-7',
      targetName: 'Açıq Hava Dağ Mənzərəli Toy Altarı',
      isCover: true,
      order: 1,
      format: 'webp',
      uploadedAt: now
    },
    {
      id: 'img-decor-8-cover',
      url: '/images/dreamart-tebii-budag-agac-kompozisiyasi.webp',
      filename: 'dreamart-tebii-budag-agac-kompozisiyasi.webp',
      altText: 'DreamArt Events təbii budaqlardan hazırlanmış unikal ağac masa kompozisiyası',
      section: 'decor_project',
      targetId: 'decor-8',
      targetName: 'Klassik Gəncə İntim Nişan və Xonça Tərtibatı',
      isCover: true,
      order: 1,
      format: 'webp',
      uploadedAt: now
    },
    {
      id: 'img-decor-9-cover',
      url: '/images/xonca-xidmeti-cover.jpg',
      filename: 'ekskluziv-bullur-qizili-xonca-main.webp',
      altText: 'Eksklüziv büllur və qızılı xonça kompozisiyası',
      section: 'decor_project',
      targetId: 'decor-9',
      targetName: 'Eksklüziv Büllur və Qızılı Xonça Kompozisiyası',
      isCover: true,
      order: 1,
      format: 'webp',
      uploadedAt: now
    },

    // 4. Restoran / Məkan Layihələri (venue_project)
    {
      id: 'img-venue-meridian-cover',
      url: '/images/dreamart-monumental-toy-sehnesi-dekoru.webp',
      filename: 'dreamart-monumental-toy-sehnesi-dekoru.webp',
      altText: 'Meridian restoranında monumental toy səhnəsi və çilçıraqlar',
      section: 'venue_project',
      targetId: 'meridian',
      targetName: 'Meridian Şadlıq Sarayı',
      isCover: true,
      order: 1,
      format: 'webp',
      uploadedAt: now
    },
    {
      id: 'img-venue-meridian-gal-1',
      url: '/images/dreamart-toy-dekoru-qizili-altar.webp',
      filename: 'dreamart-toy-dekoru-qizili-altar.webp',
      altText: 'Meridian bəy-gəlin masası qızılı tağ dekoru',
      section: 'venue_project',
      targetId: 'meridian',
      targetName: 'Meridian Şadlıq Sarayı',
      isCover: false,
      order: 2,
      format: 'webp',
      uploadedAt: now
    },
    {
      id: 'img-venue-meridian-gal-2',
      url: '/images/dreamart-banket-zali-goy-isiq-dekoru.webp',
      filename: 'dreamart-banket-zali-goy-isiq-dekoru.webp',
      altText: 'Meridian banket zalı və çilçıraq kompozisiyası',
      section: 'venue_project',
      targetId: 'meridian',
      targetName: 'Meridian Şadlıq Sarayı',
      isCover: false,
      order: 3,
      format: 'webp',
      uploadedAt: now
    },
    {
      id: 'img-venue-by-meridian-cover',
      url: '/images/dreamart-bey-gelin-masasi-cicek-tagi.webp',
      filename: 'dreamart-bey-gelin-masasi-cicek-tagi.webp',
      altText: 'By Meridian məkanında dairəvi çiçək tağları və büllur çilçıraqlı toy və nişan dekoru',
      section: 'venue_project',
      targetId: 'by-meridian',
      targetName: 'By Meridian',
      isCover: true,
      order: 1,
      format: 'webp',
      uploadedAt: now
    },
    {
      id: 'img-venue-by-meridian-gal-1',
      url: '/images/dreamart-nisan-dekoru-fotozona.webp',
      filename: 'dreamart-nisan-dekoru-fotozona.webp',
      altText: 'By Meridian zərif nişan fotozonası',
      section: 'venue_project',
      targetId: 'by-meridian',
      targetName: 'By Meridian',
      isCover: false,
      order: 2,
      format: 'webp',
      uploadedAt: now
    },
    {
      id: 'img-venue-by-meridian-gal-2',
      url: '/images/dreamart-tebii-budag-agac-kompozisiyasi.webp',
      filename: 'dreamart-tebii-budag-agac-kompozisiyasi.webp',
      altText: 'By Meridian ağac budaq masa bəzəyi',
      section: 'venue_project',
      targetId: 'by-meridian',
      targetName: 'By Meridian',
      isCover: false,
      order: 3,
      format: 'webp',
      uploadedAt: now
    },
    {
      id: 'img-venue-bagcali-cover',
      url: '/images/dreamart-restoran-qonaq-masasi-dekoru.webp',
      filename: 'dreamart-restoran-qonaq-masasi-dekoru.webp',
      altText: 'Bağçalı Saray zümrüd yaşıl süfrə və zəngin masa dekoru',
      section: 'venue_project',
      targetId: 'bagcali-saray',
      targetName: 'Bağçalı Saray',
      isCover: true,
      order: 1,
      format: 'webp',
      uploadedAt: now
    },
    {
      id: 'img-venue-bagcali-gal-1',
      url: '/images/dreamart-qala-gecesi-samdan-dekoru.webp',
      filename: 'dreamart-qala-gecesi-samdan-dekoru.webp',
      altText: 'Bağçalı Saray büllur şamdan kompozisiyası',
      section: 'venue_project',
      targetId: 'bagcali-saray',
      targetName: 'Bağçalı Saray',
      isCover: false,
      order: 2,
      format: 'webp',
      uploadedAt: now
    },
    {
      id: 'img-venue-boyuk-cover',
      url: '/images/dreamart-zal-dekoru-tavan-instalyasiyasi.webp',
      filename: 'dreamart-zal-dekoru-tavan-instalyasiyasi.webp',
      altText: 'Böyük Saray şadlıq sarayı tavan pərdələri və çilçıraq dekoru',
      section: 'venue_project',
      targetId: 'boyuk-saray',
      targetName: 'Böyük Saray',
      isCover: true,
      order: 1,
      format: 'webp',
      uploadedAt: now
    },
    {
      id: 'img-venue-boyuk-gal-1',
      url: '/images/dreamart-banket-zali-goy-isiq-dekoru.webp',
      filename: 'dreamart-banket-zali-goy-isiq-dekoru.webp',
      altText: 'Böyük Saray banket zalı qonaq masası',
      section: 'venue_project',
      targetId: 'boyuk-saray',
      targetName: 'Böyük Saray',
      isCover: false,
      order: 2,
      format: 'webp',
      uploadedAt: now
    },
    {
      id: 'img-venue-green-city-cover',
      url: 'https://images.unsplash.com/photo-1464366400600-7168b8af9bc3?auto=format&fit=crop&w=1600&q=85',
      filename: 'green-city-acig-hava-dekor-cover.webp',
      altText: 'Green City açıq hava tədbir məkanı dekoru',
      section: 'venue_project',
      targetId: 'green-city',
      targetName: 'Green City',
      isCover: true,
      order: 1,
      format: 'webp',
      uploadedAt: now
    },
    {
      id: 'img-venue-yegane-cover',
      url: 'https://images.unsplash.com/photo-1511285560929-80b456fea0bc?auto=format&fit=crop&w=1600&q=85',
      filename: 'yegane-sadliq-sarayi-cover.webp',
      altText: 'Yeganə şadlıq sarayı dekoru örtük şəkli',
      section: 'venue_project',
      targetId: 'yegane',
      targetName: 'Yeganə Şadlıq Sarayı',
      isCover: true,
      order: 1,
      format: 'webp',
      uploadedAt: now
    },

    // 5. Xonça Xidməti (xonca_service)
    {
      id: 'img-xonca-main',
      url: '/images/xonca-xidmeti-cover.jpg',
      filename: 'premium-xonca-xidmeti-main.webp',
      altText: 'Eksklüziv xonça kompozisiyası və tərtibatı',
      section: 'xonca_service',
      targetId: 'xonca-main',
      targetName: 'Əsas Xonça Təqdimatı',
      isCover: true,
      order: 1,
      format: 'webp',
      uploadedAt: now
    },
    {
      id: 'img-xonca-gal-1',
      url: '/images/dreamart-tebii-budag-agac-kompozisiyasi.webp',
      filename: 'dreamart-tebii-budag-agac-kompozisiyasi.webp',
      altText: 'Zərif dekorativ kompozisiya və xonça stendləri',
      section: 'xonca_service',
      targetId: 'xonca-main',
      targetName: 'Əsas Xonça Təqdimatı',
      isCover: false,
      order: 2,
      format: 'webp',
      uploadedAt: now
    },

    // 6. Portfolio Lookbook (portfolio_lookbook) - contains all 9 real DreamArt Events works
    {
      id: 'img-portfolio-1',
      url: '/images/dreamart-toy-dekoru-qizili-altar.webp',
      filename: 'dreamart-toy-dekoru-qizili-altar.webp',
      altText: 'DreamArt Events qızılı tağ və dəbdəbəli bəy-gəlin masası toy dekoru',
      section: 'portfolio_lookbook',
      targetId: 'portfolio-showcase',
      targetName: 'Toy Altarı və Səhnə',
      isCover: true,
      order: 1,
      format: 'webp',
      uploadedAt: now
    },
    {
      id: 'img-portfolio-2',
      url: '/images/dreamart-nisan-dekoru-fotozona.webp',
      filename: 'dreamart-nisan-dekoru-fotozona.webp',
      altText: 'DreamArt Events zərif bej parçalar və neon işıqlı nişan dekoru və fotozona',
      section: 'portfolio_lookbook',
      targetId: 'portfolio-showcase',
      targetName: 'Nişan Masası və Fotozona',
      isCover: false,
      order: 2,
      format: 'webp',
      uploadedAt: now
    },
    {
      id: 'img-portfolio-3',
      url: '/images/dreamart-zal-dekoru-tavan-instalyasiyasi.webp',
      filename: 'dreamart-zal-dekoru-tavan-instalyasiyasi.webp',
      altText: 'DreamArt Events böyük şadlıq zalı tavan pərdələri və çilçıraq zal dekoru',
      section: 'portfolio_lookbook',
      targetId: 'portfolio-showcase',
      targetName: 'Zal Tavan İnstalyasiyası',
      isCover: false,
      order: 3,
      format: 'webp',
      uploadedAt: now
    },
    {
      id: 'img-portfolio-4',
      url: '/images/dreamart-monumental-toy-sehnesi-dekoru.webp',
      filename: 'dreamart-monumental-toy-sehnesi-dekoru.webp',
      altText: 'DreamArt Events monumental toy səhnəsi və pilləli şamlar',
      section: 'portfolio_lookbook',
      targetId: 'portfolio-showcase',
      targetName: 'Monumental Toy Səhnəsi',
      isCover: false,
      order: 4,
      format: 'webp',
      uploadedAt: now
    },
    {
      id: 'img-portfolio-5',
      url: '/images/dreamart-bey-gelin-masasi-cicek-tagi.webp',
      filename: 'dreamart-bey-gelin-masasi-cicek-tagi.webp',
      altText: 'DreamArt Events dairəvi çiçək tağları və büllur çilçıraqlı bəy-gəlin masası',
      section: 'portfolio_lookbook',
      targetId: 'portfolio-showcase',
      targetName: 'Bəy-Gəlin Masası və Tağ',
      isCover: false,
      order: 5,
      format: 'webp',
      uploadedAt: now
    },
    {
      id: 'img-portfolio-6',
      url: '/images/dreamart-restoran-qonaq-masasi-dekoru.webp',
      filename: 'dreamart-restoran-qonaq-masasi-dekoru.webp',
      altText: 'DreamArt Events zümrüd yaşıl məxmər süfrə və hündür gül güldanlı masa dekoru',
      section: 'portfolio_lookbook',
      targetId: 'portfolio-showcase',
      targetName: 'Zümrüd Yaşıl Masa Tərtibatı',
      isCover: false,
      order: 6,
      format: 'webp',
      uploadedAt: now
    },
    {
      id: 'img-portfolio-7',
      url: '/images/dreamart-qala-gecesi-samdan-dekoru.webp',
      filename: 'dreamart-qala-gecesi-samdan-dekoru.webp',
      altText: 'DreamArt Events büllur şamdanlar və zərif qab-qacaqla korporativ qala dekoru',
      section: 'portfolio_lookbook',
      targetId: 'portfolio-showcase',
      targetName: 'Qala Gecəsi Büllur Şamdanlar',
      isCover: false,
      order: 7,
      format: 'webp',
      uploadedAt: now
    },
    {
      id: 'img-portfolio-8',
      url: '/images/dreamart-banket-zali-goy-isiq-dekoru.webp',
      filename: 'dreamart-banket-zali-goy-isiq-dekoru.webp',
      altText: 'DreamArt Events dəbdəbəli banket zalı, qonaq masası və çilçıraq tərtibatı',
      section: 'portfolio_lookbook',
      targetId: 'portfolio-showcase',
      targetName: 'Banket Zalı və Çilçıraqlar',
      isCover: false,
      order: 8,
      format: 'webp',
      uploadedAt: now
    },
    {
      id: 'img-portfolio-9',
      url: '/images/dreamart-tebii-budag-agac-kompozisiyasi.webp',
      filename: 'dreamart-tebii-budag-agac-kompozisiyasi.webp',
      altText: 'DreamArt Events təbii budaqlardan hazırlanmış unikal ağac masa kompozisiyası',
      section: 'portfolio_lookbook',
      targetId: 'portfolio-showcase',
      targetName: 'Təbii Budaq Ağac Kompozisiyası',
      isCover: false,
      order: 9,
      format: 'webp',
      uploadedAt: now
    },
    {
      id: 'img-portfolio-10',
      url: '/images/xonca-xidmeti-cover.jpg',
      filename: 'premium-xonca-xidmeti-main.webp',
      altText: 'DreamArt Events xonça tərtibatı vitrini',
      section: 'portfolio_lookbook',
      targetId: 'portfolio-showcase',
      targetName: 'Xonça Tərtibatı Vitrini',
      isCover: false,
      order: 10,
      format: 'webp',
      uploadedAt: now
    },

    // 7. Region Xidməti (regional_service)
    {
      id: 'img-regional-main',
      url: '/images/azerbaijan-regional-cover.jpg',
      filename: 'azerbaijan-regional-dekor-cover.webp',
      altText: 'Azərbaycan regional dekorasiya və loqistika xidməti',
      section: 'regional_service',
      targetId: 'regional-main',
      targetName: 'Azərbaycan Regional Xidmət Banneri',
      isCover: true,
      order: 1,
      format: 'webp',
      uploadedAt: now
    }
  ];
}
