import { ManagedImage } from '../src/types';

export function getInitialSeedImages(): ManagedImage[] {
  const now = new Date().toISOString();

  return [
    // 1. Ana Səhifə Hero (home_hero)
    {
      id: 'img-hero-1',
      url: 'https://images.unsplash.com/photo-1519741497674-611481863552?auto=format&fit=crop&w=2200&q=90',
      filename: 'dreamart-events-hero-slide-01.webp',
      altText: 'DreamArt Events toy və ziyafət dekorasiyası əsas banner',
      section: 'home_hero',
      targetId: 'hero-slide-1',
      targetName: 'Əsas Slayd 1 - Zövqlü Dekor Həlləri',
      isCover: true,
      order: 1,
      format: 'webp',
      uploadedAt: now
    },
    {
      id: 'img-hero-2',
      url: 'https://images.unsplash.com/photo-1511285560929-80b456fea0bc?auto=format&fit=crop&w=2200&q=90',
      filename: 'dreamart-events-hero-slide-02.webp',
      altText: 'DreamArt Events fərdi və emosional məkanlar',
      section: 'home_hero',
      targetId: 'hero-slide-2',
      targetName: 'Əsas Slayd 2 - Müasir Zəriflik',
      isCover: false,
      order: 2,
      format: 'webp',
      uploadedAt: now
    },
    {
      id: 'img-hero-3',
      url: '/images/boyuk-zal-dekor.jpg',
      filename: 'dreamart-events-hero-slide-03.webp',
      altText: 'DreamArt Events böyük şadlıq zalları və tavan instalyasiyaları',
      section: 'home_hero',
      targetId: 'hero-slide-3',
      targetName: 'Əsas Slayd 3 - Böyük Zallar və İnstalyasiyalar',
      isCover: false,
      order: 3,
      format: 'webp',
      uploadedAt: now
    },

    // 2. Xidmət Kateqoriyaları (category_cover)
    {
      id: 'img-cat-toy',
      url: 'https://images.unsplash.com/photo-1519741497674-611481863552?auto=format&fit=crop&w=1200&q=85',
      filename: 'dreamart-toy-dekoru-qapaq.webp',
      altText: 'DreamArt Events toy dekoru örtük şəkli',
      section: 'category_cover',
      targetId: 'toy-dekoru',
      targetName: 'Toy dekoru',
      isCover: true,
      order: 1,
      format: 'webp',
      uploadedAt: now
    },
    {
      id: 'img-cat-nisan',
      url: 'https://images.unsplash.com/photo-1511285560929-80b456fea0bc?auto=format&fit=crop&w=1200&q=85',
      filename: 'dreamart-nisan-dekoru-qapaq.webp',
      altText: 'DreamArt Events nişan dekoru örtük şəkli',
      section: 'category_cover',
      targetId: 'nisan-dekoru',
      targetName: 'Nişan dekoru',
      isCover: true,
      order: 1,
      format: 'webp',
      uploadedAt: now
    },
    {
      id: 'img-cat-xina',
      url: 'https://images.unsplash.com/photo-1545232979-fbf6786a34be?auto=format&fit=crop&w=1200&q=85',
      filename: 'dreamart-xina-dekoru-qapaq.webp',
      altText: 'DreamArt Events xına mərasimi dekoru örtük şəkli',
      section: 'category_cover',
      targetId: 'xina-dekoru',
      targetName: 'Xına dekoru',
      isCover: true,
      order: 1,
      format: 'webp',
      uploadedAt: now
    },
    {
      id: 'img-cat-adgunu',
      url: 'https://images.unsplash.com/photo-1464366400600-7168b8af9bc3?auto=format&fit=crop&w=1200&q=85',
      filename: 'dreamart-ad-gunu-dekoru-qapaq.webp',
      altText: 'DreamArt Events ad günü və yubiley fotozonası örtük şəkli',
      section: 'category_cover',
      targetId: 'ad-gunu-dekoru',
      targetName: 'Ad günü dekoru',
      isCover: true,
      order: 1,
      format: 'webp',
      uploadedAt: now
    },
    {
      id: 'img-cat-korporativ',
      url: 'https://images.unsplash.com/photo-1511795409834-ef04bbd61622?auto=format&fit=crop&w=1200&q=85',
      filename: 'dreamart-korporativ-dekor-qapaq.webp',
      altText: 'DreamArt Events korporativ tədbir və qala gecəsi dekoru örtük şəkli',
      section: 'category_cover',
      targetId: 'korporativ-dekor',
      targetName: 'Korporativ dekor',
      isCover: true,
      order: 1,
      format: 'webp',
      uploadedAt: now
    },
    {
      id: 'img-cat-zal',
      url: '/images/boyuk-zal-dekor.jpg',
      filename: 'dreamart-zal-dekoru-qapaq.webp',
      altText: 'DreamArt Events böyük şadlıq sarayı və zal dekorasiyası örtük şəkli',
      section: 'category_cover',
      targetId: 'zal-dekoru',
      targetName: 'Zal dekoru',
      isCover: true,
      order: 1,
      format: 'webp',
      uploadedAt: now
    },
    {
      id: 'img-cat-xonca',
      url: '/images/xonca-xidmeti-cover.jpg',
      filename: 'dreamart-xonca-xidmeti-qapaq.webp',
      altText: 'DreamArt Events milli və müasir xonça xidməti örtük şəkli',
      section: 'category_cover',
      targetId: 'xonca-xidmeti',
      targetName: 'Xonça xidməti',
      isCover: true,
      order: 1,
      format: 'webp',
      uploadedAt: now
    },

    // 3. Dekor Layihələri (decor_project)
    {
      id: 'img-decor-1-cover',
      url: 'https://images.unsplash.com/photo-1519741497674-611481863552?auto=format&fit=crop&w=1600&q=85',
      filename: 'ag-qizilgul-toy-altari-main.webp',
      altText: 'Ağ qızılgül və zərif şamlı toy altarı örtük şəkli',
      section: 'decor_project',
      targetId: 'decor-1',
      targetName: 'Ağ Qızılgül və Zərif Şamlı Toy Altarı',
      isCover: true,
      order: 1,
      format: 'webp',
      uploadedAt: now
    },
    {
      id: 'img-decor-1-gal-1',
      url: 'https://images.unsplash.com/photo-1519225421980-715cb0215aed?auto=format&fit=crop&w=1200&q=85',
      filename: 'ag-qizilgul-toy-altari-gal-1.webp',
      altText: 'Ağ qızılgül toy altarı yaxından baxış',
      section: 'decor_project',
      targetId: 'decor-1',
      targetName: 'Ağ Qızılgül və Zərif Şamlı Toy Altarı',
      isCover: false,
      order: 2,
      format: 'webp',
      uploadedAt: now
    },
    {
      id: 'img-decor-2-cover',
      url: 'https://images.unsplash.com/photo-1511285560929-80b456fea0bc?auto=format&fit=crop&w=1600&q=85',
      filename: 'pudra-cehrayi-nisan-masasi-main.webp',
      altText: 'Pudra çəhrayı və qızılı pastel nişan masası örtük şəkli',
      section: 'decor_project',
      targetId: 'decor-2',
      targetName: 'Pudra Çəhrayı və Qızılı Pastel Nişan Masası',
      isCover: true,
      order: 1,
      format: 'webp',
      uploadedAt: now
    },
    {
      id: 'img-decor-3-cover',
      url: 'https://images.unsplash.com/photo-1545232979-fbf6786a34be?auto=format&fit=crop&w=1600&q=85',
      filename: 'kraliyyet-mexmeri-xina-dekoru-main.webp',
      altText: 'Kraliyyət məxməri və şam kompozisiyalı xına dekoru',
      section: 'decor_project',
      targetId: 'decor-3',
      targetName: 'Kraliyyət Məxməri və Şam Kompozisiyalı Xına Dekoru',
      isCover: true,
      order: 1,
      format: 'webp',
      uploadedAt: now
    },
    {
      id: 'img-decor-4-cover',
      url: 'https://images.unsplash.com/photo-1464366400600-7168b8af9bc3?auto=format&fit=crop&w=1600&q=85',
      filename: 'krem-qizili-ad-gunu-fotozona-main.webp',
      altText: 'Krem və qızılı işıqlı estetik ad günü fotozonası',
      section: 'decor_project',
      targetId: 'decor-4',
      targetName: 'Krem Və Qızılı İşıqlı Estetik Ad Günü Fotozonası',
      isCover: true,
      order: 1,
      format: 'webp',
      uploadedAt: now
    },
    {
      id: 'img-decor-5-cover',
      url: 'https://images.unsplash.com/photo-1511795409834-ef04bbd61622?auto=format&fit=crop&w=1600&q=85',
      filename: 'qala-sam-yemeyi-korporativ-main.webp',
      altText: 'Qala şam yeməyi və korporativ tədbir tərtibatı',
      section: 'decor_project',
      targetId: 'decor-5',
      targetName: 'Qala Şam Yeməyi və Korporativ Tədbir Tərtibatı',
      isCover: true,
      order: 1,
      format: 'webp',
      uploadedAt: now
    },
    {
      id: 'img-decor-6-cover',
      url: '/images/boyuk-zal-dekor.jpg',
      filename: 'panoramik-sadliq-zali-tavan-main.webp',
      altText: 'Panoramik şadlıq zalı və tavan işıq instalyasiyası',
      section: 'decor_project',
      targetId: 'decor-6',
      targetName: 'Panoramik Şadlıq Zalı və Tavan İşıq İnstalyasiyası',
      isCover: true,
      order: 1,
      format: 'webp',
      uploadedAt: now
    },
    {
      id: 'img-decor-7-cover',
      url: 'https://images.unsplash.com/photo-1465495976277-4387d4b0b4c6?auto=format&fit=crop&w=1600&q=85',
      filename: 'aciq-hava-dag-menzereli-toy-altari-main.webp',
      altText: 'Açıq hava dağ mənzərəli toy altarı',
      section: 'decor_project',
      targetId: 'decor-7',
      targetName: 'Açıq Hava Dağ Mənzərəli Toy Altarı',
      isCover: true,
      order: 1,
      format: 'webp',
      uploadedAt: now
    },
    {
      id: 'img-decor-8-cover',
      url: 'https://images.unsplash.com/photo-1519225421980-715cb0215aed?auto=format&fit=crop&w=1600&q=85',
      filename: 'klassik-gence-nisan-masasi-main.webp',
      altText: 'Klassik Gəncə intim nişan və xonça tərtibatı',
      section: 'decor_project',
      targetId: 'decor-8',
      targetName: 'Klassik Gəncə İntim Nişan və Xonça Tərtibatı',
      isCover: true,
      order: 1,
      format: 'webp',
      uploadedAt: now
    },
    {
      id: 'img-decor-9-cover',
      url: '/images/xonca-xidmeti-cover.jpg',
      filename: 'ekskluziv-bullur-qizili-xonca-main.webp',
      altText: 'Eksklüziv büllur və qızılı xonça kompozisiyası',
      section: 'decor_project',
      targetId: 'decor-9',
      targetName: 'Eksklüziv Büllur və Qızılı Xonça Kompozisiyası',
      isCover: true,
      order: 1,
      format: 'webp',
      uploadedAt: now
    },

    // 4. Restoran / Məkan Layihələri (venue_project)
    {
      id: 'img-venue-meridian-cover',
      url: 'https://images.unsplash.com/photo-1519167758481-83f550bb49b3?auto=format&fit=crop&w=1600&q=85',
      filename: 'meridian-sadliq-sarayi-cover.webp',
      altText: 'Meridian şadlıq sarayı zal dekoru örtük şəkli',
      section: 'venue_project',
      targetId: 'meridian',
      targetName: 'Meridian Şadlıq Sarayı',
      isCover: true,
      order: 1,
      format: 'webp',
      uploadedAt: now
    },
    {
      id: 'img-venue-by-meridian-cover',
      url: 'https://images.unsplash.com/photo-1519741497674-611481863552?auto=format&fit=crop&w=1600&q=85',
      filename: 'by-meridian-dekoru-cover.webp',
      altText: 'By Meridian məkanında toy və ziyafət dekoru',
      section: 'venue_project',
      targetId: 'by-meridian',
      targetName: 'By Meridian',
      isCover: true,
      order: 1,
      format: 'webp',
      uploadedAt: now
    },
    {
      id: 'img-venue-bagcali-cover',
      url: 'https://images.unsplash.com/photo-1511795409834-ef04bbd61622?auto=format&fit=crop&w=1600&q=85',
      filename: 'bagcali-saray-dekoru-cover.webp',
      altText: 'Bağçalı Saray zal tərtibatı örtük şəkli',
      section: 'venue_project',
      targetId: 'bagcali-saray',
      targetName: 'Bağçalı Saray',
      isCover: true,
      order: 1,
      format: 'webp',
      uploadedAt: now
    },
    {
      id: 'img-venue-boyuk-cover',
      url: '/images/boyuk-zal-dekor.jpg',
      filename: 'boyuk-saray-dekoru-cover.webp',
      altText: 'Böyük Saray şadlıq sarayı tavan və səhnə dekoru',
      section: 'venue_project',
      targetId: 'boyuk-saray',
      targetName: 'Böyük Saray',
      isCover: true,
      order: 1,
      format: 'webp',
      uploadedAt: now
    },
    {
      id: 'img-venue-green-city-cover',
      url: 'https://images.unsplash.com/photo-1464366400600-7168b8af9bc3?auto=format&fit=crop&w=1600&q=85',
      filename: 'green-city-acig-hava-dekor-cover.webp',
      altText: 'Green City açıq hava tədbir məkanı dekoru',
      section: 'venue_project',
      targetId: 'green-city',
      targetName: 'Green City',
      isCover: true,
      order: 1,
      format: 'webp',
      uploadedAt: now
    },
    {
      id: 'img-venue-yegane-cover',
      url: 'https://images.unsplash.com/photo-1511285560929-80b456fea0bc?auto=format&fit=crop&w=1600&q=85',
      filename: 'yegane-sadliq-sarayi-cover.webp',
      altText: 'Yeganə şadlıq sarayı dekoru örtük şəkli',
      section: 'venue_project',
      targetId: 'yegane',
      targetName: 'Yeganə Şadlıq Sarayı',
      isCover: true,
      order: 1,
      format: 'webp',
      uploadedAt: now
    },

    // 5. Xonça Xidməti (xonca_service)
    {
      id: 'img-xonca-main',
      url: '/images/xonca-xidmeti-cover.jpg',
      filename: 'premium-xonca-xidmeti-main.webp',
      altText: 'Eksklüziv xonça kompozisiyası və tərtibatı',
      section: 'xonca_service',
      targetId: 'xonca-main',
      targetName: 'Əsas Xonça Təqdimatı',
      isCover: true,
      order: 1,
      format: 'webp',
      uploadedAt: now
    },
    {
      id: 'img-xonca-gal-1',
      url: 'https://images.unsplash.com/photo-1519741497674-611481863552?auto=format&fit=crop&w=1200&q=85',
      filename: 'nisan-xoncalari-dest.webp',
      altText: 'Zərif lentli və güllü nişan xonçaları dəsti',
      section: 'xonca_service',
      targetId: 'xonca-main',
      targetName: 'Əsas Xonça Təqdimatı',
      isCover: false,
      order: 2,
      format: 'webp',
      uploadedAt: now
    },

    // 6. Portfolio Lookbook (portfolio_lookbook)
    {
      id: 'img-portfolio-1',
      url: 'https://images.unsplash.com/photo-1519741497674-611481863552?auto=format&fit=crop&w=1600&q=85',
      filename: 'portfolio-toy-altari-01.webp',
      altText: 'DreamArt Events toy altarı və zərif şam kompozisiyası',
      section: 'portfolio_lookbook',
      targetId: 'portfolio-showcase',
      targetName: 'Toy Altarı Vitrini',
      isCover: true,
      order: 1,
      format: 'webp',
      uploadedAt: now
    },
    {
      id: 'img-portfolio-2',
      url: '/images/boyuk-zal-dekor.jpg',
      filename: 'portfolio-zal-tavan-02.webp',
      altText: 'DreamArt Events böyük zal tavan instalyasiyası vitrini',
      section: 'portfolio_lookbook',
      targetId: 'portfolio-showcase',
      targetName: 'Zal Tavan İnstalyasiyası',
      isCover: false,
      order: 2,
      format: 'webp',
      uploadedAt: now
    },
    {
      id: 'img-portfolio-3',
      url: 'https://images.unsplash.com/photo-1511285560929-80b456fea0bc?auto=format&fit=crop&w=1600&q=85',
      filename: 'portfolio-nisan-masasi-03.webp',
      altText: 'DreamArt Events pastel nişan masası vitrini',
      section: 'portfolio_lookbook',
      targetId: 'portfolio-showcase',
      targetName: 'Nişan Masası Vitrini',
      isCover: false,
      order: 3,
      format: 'webp',
      uploadedAt: now
    },
    {
      id: 'img-portfolio-4',
      url: '/images/xonca-xidmeti-cover.jpg',
      filename: 'portfolio-xonca-kompozisiya-04.webp',
      altText: 'DreamArt Events xonça tərtibatı vitrini',
      section: 'portfolio_lookbook',
      targetId: 'portfolio-showcase',
      targetName: 'Xonça Tərtibatı Vitrini',
      isCover: false,
      order: 4,
      format: 'webp',
      uploadedAt: now
    },

    // 7. Region Xidməti (regional_service)
    {
      id: 'img-regional-main',
      url: '/images/azerbaijan-regional-cover.jpg',
      filename: 'azerbaijan-regional-dekor-cover.webp',
      altText: 'Azərbaycan regional dekorasiya və loqistika xidməti',
      section: 'regional_service',
      targetId: 'regional-main',
      targetName: 'Azərbaycan Regional Xidmət Banneri',
      isCover: true,
      order: 1,
      format: 'webp',
      uploadedAt: now
    }
  ];
}
